language: go

go:
  - 1.5
  - 1.6
  - tip

sudo: required

services:
  - docker

before_script:
  - go install ./...
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - gometalinter --deadline 60s ./..
  - docker build .
